---
- name: host test
  hosts: all

  tasks:
    - name : check date
      shell: date
      notify: restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
      
