---
- name: host test
  hosts: all

  tasks:
    - name : check date
      shell: date
      notify: restart nginx
    - name: add the Vagrant hosts to the inventory
      add_host: >
            name=vagrant
            ansible_ssh_host=127.0.0.1
            ansible_ssh_port=2222
            ansible_ssh_user=vagrant
            ansible_ssh_private_key_file=/Users/lorinhochstein/.vagrant.d/
            insecure_private_key
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
      
