---
- name: host test
  hosts: all
  vars: 
    file: hosttest.yml
  tasks:
    - name : check date
      shell: date
      notify: restart nginx
    - debug : var=file
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
      
